@REQUESTS_ENV_HOST=http://localhost:3000
@id=1
@AUTH_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTY5NzkxNTkwOCwiZXhwIjoxNzAwNTA3OTA4fQ.XZ1VHD4d-XWeAGTq_BQNCjP8Y-9tNE20YYHb9J-DmI0

### Simple request

GET {{REQUESTS_ENV_HOST}}

### Login

POST {{REQUESTS_ENV_HOST}}/login
Content-Type: application/json

{ 
  "username": "johndoe", 
  "password": "12345678" 
}

### Password Reset

PATCH {{REQUESTS_ENV_HOST}}/private/utils/user/{{id}}/password/reset
Content-Type: application/json

{
  "password": "12345678"
}

### Insertar transacción

POST {{REQUESTS_ENV_HOST}}/user/transaction
Content-Type: application/json 
Authorization: Bearer {{AUTH_TOKEN}}

{
  "amount": 1234, 
  "detail": "Seat 1, Row 3, Section 1"
}
