@REQUESTS_ENV_HOST=http://localhost:3000

@ADMIN_AUTH_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTY5NzkxNTkwOCwiZXhwIjoxNzAwNTA3OTA4fQ.XZ1VHD4d-XWeAGTq_BQNCjP8Y-9tNE20YYHb9J-DmI0
@CUSTOMER_AUTH_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImlhdCI6MTY5NzkzODYwNCwiZXhwIjoxNzAwNTMwNjA0fQ.U1b4t4FbnMPLOJU4DF0ZfnejnsPGhIkzATdPizFm9kM

@id=2
### Simple request

GET {{REQUESTS_ENV_HOST}}

### Login

POST {{REQUESTS_ENV_HOST}}/login
Content-Type: application/json

{ 
  "username": "janedoe", 
  "password": "12345678"
}

### Password Reset


PATCH {{REQUESTS_ENV_HOST}}/private/utils/user/{{id}}/password/reset
Content-Type: application/json
Authorization: Bearer {{ADMIN_AUTH_TOKEN}}

{
  "password": "12345678"
}

### Insertar transacción

POST {{REQUESTS_ENV_HOST}}/user/transaction
Content-Type: application/json 
Authorization: Bearer {{CUSTOMER_AUTH_TOKEN}}

{
  "amount": 1234, 
  "detail": "Seat 1, Row 3, Section 1"
}

### Obtener transacciones de un usuario**

GET {{REQUESTS_ENV_HOST}}/user?related=transactions
Authorization: Bearer {{CUSTOMER_AUTH_TOKEN}}

### Obtener lista de socios y sus totales*
  
GET {{REQUESTS_ENV_HOST}}/private/users?related=transactions
Authorization: Bearer {{ADMIN_AUTH_TOKEN}}

