@REQUESTS_ENV_HOST=http://localhost:3000

GET localhost:3000

### Simple request

GET {{REQUESTS_ENV_HOST}}

### Login

GET {{REQUESTS_ENV_HOST}}/login

### Password Reset

GET {{REQUESTS_ENV_HOST}}/private/utils/user/{{ _.id }}/password/reset
